package com.input.userdetails;

import com.j256.ormlite.field.DatabaseField;

public class UserDetails {


	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField
	String firstName;
	@DatabaseField
	String lastName;
	@DatabaseField
	String emailId;
	@DatabaseField
	String password;

	UserDetails(){
		// no arg constructor needed by ORMLite
	}
	
	UserDetails(String fn, String ln, String email, String pass){
		firstName = fn;
		lastName = ln;
		emailId = email;
		password = pass;
	}
	
	@Override
	public String toString(){
		StringBuilder sb = new StringBuilder();
		sb.append("id: ").append(id).append("  First Name: ").append(firstName).append("   Last Name: ").append(lastName);
		sb.append("   Email Id: ").append(emailId).append("   Password: ").append(password);
		return sb.toString();
	}



}
